/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : BookId,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'author' : string,
  'category' : string,
}
export type BookId = string;
export type ChallengeId = string;
export type ExternalBlob = Uint8Array;
export type GroupId = bigint;
export interface GroupMessage {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'groupId' : GroupId,
  'timestamp' : Time,
}
export type InviteCode = string;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type MessageId = string;
export interface QuizChallenge {
  'id' : ChallengeId,
  'answers' : Array<string>,
  'winner' : [] | [UserId],
  'questions' : Array<string>,
  'challenger' : UserId,
  'opponent' : UserId,
}
export interface RegistrationInput {
  'username' : string,
  'inviteCode' : InviteCode,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Uint8Array;
export interface UserProfile {
  'status' : { 'active' : null } |
    { 'banned' : null },
  'hasPaid' : boolean,
  'username' : string,
  'invites' : bigint,
  'rank' : bigint,
  'inviteCode' : string,
  'quizWins' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'checkBookAccess' : ActorMethod<[Principal], boolean>,
  'createBook' : ActorMethod<[Book], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createUserProfile' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getBook' : ActorMethod<[string], Book>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendsCount' : ActorMethod<[Principal], bigint>,
  'getGroupMessages' : ActorMethod<[GroupId], Array<GroupMessage>>,
  'getHighestScoredChallenge' : ActorMethod<[], [] | [QuizChallenge]>,
  'getLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getPendingFriendRequests' : ActorMethod<[Principal], Array<Principal>>,
  'getSentFriendRequests' : ActorMethod<[Principal], Array<Principal>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserMessages' : ActorMethod<[Principal], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markUserAsPaid' : ActorMethod<[Principal], undefined>,
  'registerWithInvite' : ActorMethod<[RegistrationInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendGroupMessage' : ActorMethod<[GroupMessage], bigint>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];