/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Book = IDL.Record({
  'id' : BookId,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'category' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'status' : IDL.Variant({ 'active' : IDL.Null, 'banned' : IDL.Null }),
  'hasPaid' : IDL.Bool,
  'username' : IDL.Text,
  'invites' : IDL.Nat,
  'rank' : IDL.Nat,
  'inviteCode' : IDL.Text,
  'quizWins' : IDL.Nat,
});
export const GroupId = IDL.Nat;
export const Time = IDL.Int;
export const GroupMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'groupId' : GroupId,
  'timestamp' : Time,
});
export const ChallengeId = IDL.Text;
export const UserId = IDL.Vec(IDL.Nat8);
export const QuizChallenge = IDL.Record({
  'id' : ChallengeId,
  'answers' : IDL.Vec(IDL.Text),
  'winner' : IDL.Opt(UserId),
  'questions' : IDL.Vec(IDL.Text),
  'challenger' : UserId,
  'opponent' : UserId,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const MessageId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const InviteCode = IDL.Text;
export const RegistrationInput = IDL.Record({
  'username' : IDL.Text,
  'inviteCode' : InviteCode,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'checkBookAccess' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'createBook' : IDL.Func([Book], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createUserProfile' : IDL.Func([IDL.Text], [], []),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendsCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getGroupMessages' : IDL.Func([GroupId], [IDL.Vec(GroupMessage)], ['query']),
  'getHighestScoredChallenge' : IDL.Func(
      [],
      [IDL.Opt(QuizChallenge)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getPendingFriendRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getSentFriendRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markUserAsPaid' : IDL.Func([IDL.Principal], [], []),
  'registerWithInvite' : IDL.Func([RegistrationInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendGroupMessage' : IDL.Func([GroupMessage], [IDL.Nat], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Book = IDL.Record({
    'id' : BookId,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'category' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'status' : IDL.Variant({ 'active' : IDL.Null, 'banned' : IDL.Null }),
    'hasPaid' : IDL.Bool,
    'username' : IDL.Text,
    'invites' : IDL.Nat,
    'rank' : IDL.Nat,
    'inviteCode' : IDL.Text,
    'quizWins' : IDL.Nat,
  });
  const GroupId = IDL.Nat;
  const Time = IDL.Int;
  const GroupMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'groupId' : GroupId,
    'timestamp' : Time,
  });
  const ChallengeId = IDL.Text;
  const UserId = IDL.Vec(IDL.Nat8);
  const QuizChallenge = IDL.Record({
    'id' : ChallengeId,
    'answers' : IDL.Vec(IDL.Text),
    'winner' : IDL.Opt(UserId),
    'questions' : IDL.Vec(IDL.Text),
    'challenger' : UserId,
    'opponent' : UserId,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const MessageId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const InviteCode = IDL.Text;
  const RegistrationInput = IDL.Record({
    'username' : IDL.Text,
    'inviteCode' : InviteCode,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'checkBookAccess' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'createBook' : IDL.Func([Book], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createUserProfile' : IDL.Func([IDL.Text], [], []),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendsCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getGroupMessages' : IDL.Func(
        [GroupId],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getHighestScoredChallenge' : IDL.Func(
        [],
        [IDL.Opt(QuizChallenge)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getPendingFriendRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getSentFriendRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markUserAsPaid' : IDL.Func([IDL.Principal], [], []),
    'registerWithInvite' : IDL.Func([RegistrationInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendGroupMessage' : IDL.Func([GroupMessage], [IDL.Nat], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };